config/routes.rb
Rails.application.routes.draw do
  resources :users, to: [:new, :create, :show]

  resources :users, only: [] do
    get "redeem", to: "rewards#redeem"
  end

  namespace :admin do
    patch "add_points", to: "users#add_points"
    resources :rewards, except: [:show, :index]
  end

  resources :rewards, only: [:show, :index]

  root "users#new"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  validates :cost, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :rewards

  enum role: %w(default admin)

  def is_admin?
    role == "admin"
  end
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < AdminController
  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)

    if @reward.save
      flash[:notice] = "Reward created"
      redirect_to @reward
    else
      flash[:errors] = "Reward not created"
      render :new
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find_by(params[:name])

    if @reward.update(reward_params)
      redirect_to @reward
    else
      render file: "/public/404" unless current_admin?
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.delete

    redirect_to rewards_path
  end


    private

    def reward_params
      params.require(:reward).permit(:name, :cost)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def add_points
    @user = User.find_by(username: params[:user][:username])
    @user.points += params[:user][:points].to_i
    @user.save
    redirect_to @user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_admin?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.is_admin?
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def show
    @reward = Reward.find(params[:id])
  end

  def index
    @rewards = Reward.all
  end

  def redeem
    @user = User.find(params[:user_id])
    @reward = Reward.find(params[:format])

    if @user.points >= @reward.cost
      cost = @reward.cost
      @user.update(points: (@user.points - cost), redeemed_points: (@user.redeemed_points + cost))
      @user.rewards << @reward

      redirect_to @user
    end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:errors] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      # insert sad path here
    end
  end

  def show
    @user = User.find(params[:id])
    @rewards = @user.rewards
  end

    private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rewards/edit.html.erb
<h1>Edit reward</h1>
<%= form_for [:admin, @reward], url: admin_reward_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cost %>
  <%= f.select :cost, [10, 100, 1000] %>

  <%= f.submit "Change reward" %>
<% end %>

app/views/admin/rewards/new.html.erb
<h1>Create a new reward</h1>
<%= form_for [:admin, @reward] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :cost %>
  <%= f.select :cost, [10, 100, 1000] %>

  <%= f.submit "Create reward" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= current_user.username %>
    <%= link_to "Logout", logout_path, method: :delete %>
    <%= current_user.points %> points
  <% end %>
<%= yield %>

</body>
</html>

app/views/rewards/index.html.erb
<h1>Rewards</h1>
<% @rewards.each do |reward| %>
  <%= reward.name %>: <%= reward.cost %>
  <%= reward.name %>: <%= reward.cost %>
  <% if current_user && current_user.is_admin? %>
    <%= link_to "Edit #{reward.name}", edit_admin_reward_path(reward) %>
    <%= link_to "Delete #{reward.name}", admin_reward_path(reward), method:
      :delete %>
  <% elsif current_user %>
    <%= link_to "Redeem points for #{reward.name}", user_redeem_path(current_user, reward) %>
  <% end %>
<% end %>

app/views/rewards/show.html.erb
<h1>Reward page</h1>
<%= @reward.name %>: <%= @reward.cost %>

app/views/users/index.html.erb
<h1>Users page</h1>
<% @users.each do |user| %>
  <%= user.username %>
  <%= link_to user.username, user %>
<% end %>

app/views/users/new.html.erb
<h1>Create new account</h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<% if @user.is_admin? %>
  Welcome admin <%= @user.username %>
<% elsif current_user == @user %>
  <h1>Show me the <%= @user.username %></h1>
  <br>
  <h3><%= @user.username %>'s rewards</h3>
  <br>
  <% @rewards.each do |reward| %>
    <%= reward.name %>
  <% end %>
<% end %>

<% if current_user && current_user.is_admin? %>
  <%= link_to "Create new reward", new_admin_reward_path %>
  <br>
  <%= form_for @user, url: "/admin/add_points" do |f| %>
    <%= f.label :points %>
    <%= f.select :points, [10, 100, 1000] %>
    <%= f.hidden_field :username, value: @user.username %>
    <%= f.submit "Give #{@user.username} points" %>
  <% end %>
<% end %>